# Programming tutorial 1.3 

*[CEGM1000 MUDE](http://mude.citg.tudelft.nl/)*

*Written by: `Berend Bouvy`*



## Introduction

In the last tutorial we have covered the basics of Python programming, including variables, data types, and control structures. We also introduced some fundamental programming concepts such as loops and conditionals. In this tutorial we will take a closer look at functions and how to use them effectively in your code. We will not only use built-in functions but also learn how to define our own functions or import them from external libraries. 

Throughout this tutorial, we will also focus on file handling in Python, including reading from and writing to files. This is an essential skill, since we will be working a lot with data stored in files.



### Useful tools

During coding, you will often need to look up how certain functions work. There are several useful tools to help you with this:
- The [Python documentation](https://docs.python.org/3/) or library documentation such as [NumPy](https://numpy.org/doc/stable/) and [Pandas](https://pandas.pydata.org/pandas-docs/stable/) are great resources.
- AI tools like [ChatGPT](https://chat.openai.com/) and [Copilot](https://github.com/features/copilot).
- Online forums and communities such as [Stack Overflow](https://stackoverflow.com/).


## Python packages

for this assignment we will be using the following packages:
- `numpy`: for numerical operations
- `pandas`: for data manipulation and analysis
- `os`: for interacting with the operating system

These should be installed in your Python environment. If you haven't installed them yet, you can do so using pip:

```bash
pip install numpy
```


<div style="background-color:#AABAB2; color: black; width:90%; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>

$\text{Task 1.1:}$

Let's start by importing the necessary libraries.

```python
import numpy as np
import pandas as pd
import os
```

In [1]:
import numpy as np
import pandas as pd
import os

### Numpy
Numpy (numpy documentation: https://numpy.org/doc/stable/) is one of the most popular libraries for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures. Numpy is particularly useful for handling large datasets and performing complex mathematical operations efficiently. You will be using this library extensively throughout MUDE.

We will start by creating a simple array using Numpy after which we will focus on indexing and slicing. Indexing and slicing works similarly to Python lists, but with some additional features. 

A list of useful numpy functions:

- np.array(): Create an array
- np.arange(): Create an array with a range of values
- np.zeros(): Create an array filled with zeros
- np.ones(): Create an array filled with ones
- np.eye(): Create an identity matrix
- np.reshape(): Reshape an array
- np.transpose(): Transpose an array
- np.concatenate(): Concatenate arrays
- np.split(): Split an array
- np.mean(): Compute the mean of an array
- np.sum(): Compute the sum of an array
- np.max(): Find the maximum value in an array
- np.min(): Find the minimum value in an array
- np.std(): Compute the standard deviation of an array
- np.dot(): Compute the dot product of two arrays
- np.cross(): Compute the cross product of two arrays
- np.linalg.inv(): Compute the inverse of a matrix
- np.linalg.det(): Compute the determinant of a matrix
- np.random.rand(): Generate random numbers
- np.random.randn(): Generate random numbers from a standard normal distribution


In [ ]:
# Create a 1D array

# Create a 2D array

# Append a new row to the 2D array

In [ ]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
print(f"array_1d has dtype {array_1d.dtype}, shape {array_1d.shape}, size {array_1d.size}")

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
print(f"array_2d has dtype {array_2d.dtype}, shape {array_2d.shape}, size {array_2d.size}")

# Append a new row to the 2D array
array_2d2 = np.append(array_2d, [[7, 8, 9]], axis=0)
print(array_2d2)



[1 2 3 4 5]
array_1d has dtype int64, shape (5,), size 5
[[1 2 3]
 [4 5 6]]
array_2d has dtype int64, shape (2, 3), size 6
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<div style="background-color:#AABAB2; color: black; width:90%; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>

$\text{Task 1.2:}$

We will now create a np.array with 10 rows and 3 columns. The first column is filled from 1 to 10, the second column is filled with the squares of the first column, and the third column is filled with the cubes of the first column. After we have created the array we will save it to a file.

I will show you two ways to do this:
- Starting with an empty array and filling it in a loop.
- creating 3 separate arrays for each column and then combining them.


In [ ]:
# Method 1

# Method 2

# Lets check

# save the file as csv


In [23]:
# Method 1
my_array1 = np.zeros((10, 3))
first_col = np.arange(1, 11)
for i in range(3):
    my_array1[:, i] = first_col ** (i + 1)

print(my_array1)

# Method 2
first_col = np.arange(1, 11)
second_col = first_col ** 2
third_col = first_col ** 3
my_array2 = np.column_stack((first_col, second_col, third_col))
print(my_array2)

# Lets check
print(my_array1 == my_array2)

# save the file as csv
np.savetxt("my_array.csv", my_array1, delimiter=",", header="col1,col2,col3", comments='', fmt='%d')

[[   1.    1.    1.]
 [   2.    4.    8.]
 [   3.    9.   27.]
 [   4.   16.   64.]
 [   5.   25.  125.]
 [   6.   36.  216.]
 [   7.   49.  343.]
 [   8.   64.  512.]
 [   9.   81.  729.]
 [  10.  100. 1000.]]
[[   1    1    1]
 [   2    4    8]
 [   3    9   27]
 [   4   16   64]
 [   5   25  125]
 [   6   36  216]
 [   7   49  343]
 [   8   64  512]
 [   9   81  729]
 [  10  100 1000]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## os
Now that we have our data saved in a CSV file, we can use the `os` module to interact with the file system. For example, we can check if the file exists, remove it, or rename it.

some useful os functions:
- `os.path.exists(path)`: Check if a file or directory exists
- `os.remove(path)`: Remove a file
- `os.rename(old, new)`: Rename a file or directory
- `os.listdir(path)`: List all files and directories in a directory
- `os.getcwd()`: Get the current working directory
- `os.chdir(path)`: Change the current working directory
- `os.mkdir(path)`: Create a new directory
- `os.makedirs(path)`: Create a new directory and all intermediate directories
- `os.path.join(path, *paths)`: Join one or more path components intelligently


In [24]:
# List all files in the current directory
files = os.listdir()
print(files)

# Rename a file
old_name = "my_array.csv"
new_name = "data.csv"
os.rename(old_name, new_name)

# Get the current working directory
current_dir = os.getcwd()
print(current_dir)


['data.csv', 'my_array.csv', 'PT1_3.ipynb']


FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'my_array.csv' -> 'data.csv'

<div style="background-color:#AABAB2; color: black; width:90%; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>

$\text{Task 1.3:}$

if/elif/else statements. We will write a program that checks the age of a person and prints whether they are a child, teenager, or adult.


In [ ]:
my_age = 20
my_gender = "male"

if my_age < 13:
    if my_gender == "male":
        print("You are a boy.")
    else:
        print("You are a girl.")
elif my_age < 20:
    print("You are a teenager.")
else:
    print("You are an adult.")

<div style="background-color:#AABAB2; color: black; width:90%; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>

$\text{Task 1.4:}$

The final structure we will investigate is the for loop. For loops allow us to iterate over a sequence (like a list or a string) and perform an action for each item in that sequence. We will create a simple program that finds the maximum value in a list of numbers.


In [ ]:
for i in [1, 2, 3, 4, 5]:
    print(i)

for i in [1, 2, 3, 4, 5]:
    print(i*2)

for i in 'Hello':
    print(i)

for i, j in enumerate(['a', 'b', 'c']):
    print(f"the index is {i} and the value is {j}")
    
my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
current_max = my_list[0]
for num in my_list:
    if num > current_max:
        print(f"New maximum found: {num}")
        current_max = num
print(f"The maximum value in the list is {current_max}")


1
2
3
4
5
2
4
6
8
10
H
e
l
l
o
the index is 0 and the value is a
the index is 1 and the value is b
the index is 2 and the value is c
New maximum found: 4
New maximum found: 5
New maximum found: 9
The maximum value in the list is 9


<div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc;">
  <div style="display: flex; justify-content: flex-end; gap: 20px; align-items: center;">
    <a rel="MUDE" href="http://mude.citg.tudelft.nl/">
      <img alt="MUDE" style="width:100px; height:auto;" src="https://gitlab.tudelft.nl/mude/public/-/raw/main/mude-logo/MUDE_Logo-small.png" />
    </a>
    <a rel="TU Delft" href="https://www.tudelft.nl/en/ceg">
      <img alt="TU Delft" style="width:100px; height:auto;" src="https://gitlab.tudelft.nl/mude/public/-/raw/main/tu-logo/TU_P1_full-color.png" />
    </a>
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
      <img alt="Creative Commons License" style="width:88px; height:auto;" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
    </a>
  </div>
  <div style="font-size: 75%; margin-top: 10px; text-align: right;">
    &copy; Copyright 2025 <a rel="MUDE" href="http://mude.citg.tudelft.nl/">MUDE</a> TU Delft. 
    This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0 License</a>.
  </div>
</div>